project:
  type: website

website:
  title: "Open science and FAIR data for personal light exposure: Seminar"
  site-url: https://tscnlab.github.io/Zauner_tropical_light/
  repo-url: https://github.com/tscnlab/Zauner_tropical_light
  issue-url: https://github.com/tscnlab/Zauner_tropical_light/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/tscnlab/Zauner_tropical_light
        aria-label: Quarto GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

  
date: last-modified

language:
  title-block-published: "Last modified:"
